//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a76ba2_remindme12Entities : DbContext
    {
        public db_a76ba2_remindme12Entities()
            : base("name=db_a76ba2_remindme12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTMENTMASTER> DEPARTMENTMASTERs { get; set; }
        public virtual DbSet<EMPLOYEEMASTER> EMPLOYEEMASTERs { get; set; }
        public virtual DbSet<PROJECTEMPLOYEELINKING> PROJECTEMPLOYEELINKINGs { get; set; }
        public virtual DbSet<PROJECTMASTER> PROJECTMASTERs { get; set; }
    }
}
