//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEEMASTER
    {
        public string EMP_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string DEPARTMENTID { get; set; }
        public string PASSWORD { get; set; }
    }
}
