//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTMASTER
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PROJECTMGR { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDATE { get; set; }
    }
}
